name: dev

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: yarn install
        run: yarn install
      - name: yarn ci
        run: yarn ci
