name: CI

on: 
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: yarn install & yarn ci
      run: |
        yarn
        yarn ci
