name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: yarn install
        run: yarn install
      - name: yarn ci
        run: yarn ci
      - name: semantic release
        uses: docker://ellerbrock/alpine-bash-git
        with:
          args: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_ACTION: true
#      - name: publish
#        uses: actions/npm@master
#        with:
#          args: "publish --access public"
#        env:
#          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
