name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: yarn install
        run: yarn install
      - name: yarn ci
        run: yarn ci
      - name: publish
        uses: actions/npm@master
        args: publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
